packit/deployment

openshift/deployment-fedmsg.yml.j2
openshift/deployment-worker.yml.j2
openshift/deployment.yml.j2
openshift/pvc-worker.yml
playbooks/deploy.yml

I have added two new hooks:
- branch `master` -> `docker.io/usercont/packit-service:stg`
- branch `stable` -> `docker.io/usercont/packit-service:prod`
https://cloud.docker.com/u/usercont/repository/docker/usercont/packit-service/builds

template deployments to be able to use different image for prod/stg

---

openshift/deployment-worker.yml.j2

worker, readiness check: use status

---

Makefile
playbooks/deploy.yml

According to the official [docs](https://docs.ansible.com/ansible/latest/modules/k8s_module.html) `verify_ssl` is an alias for the `validate_certs`.

keep verify_ssl as it works for both 2.7 and 2.8

---

openshift/cmap-packit-httpd-conf.yml.j2

I spent whole hour debugging where the heck is `httpd` reading (wsgi script, i.e. packit-service) sources from and realized it's not `/usr/local/lib/python3.7/site-packages/packit_service`
into which I was volume mounting my current code,
but from `/src/` where the original sources were still stored.

[httpd-conf] remove 'WSGIPythonPath /src'

---

README.md
haxxx/Dockerfile
haxxx/README.md
haxxx/import-images.sh
haxxx/job-import-images.yml
openshift/imagestream-fedmsg.yml.j2
openshift/imagestream-worker.yml.j2
openshift/imagestream.yml.j2
playbooks/deploy.yml
vars/template.yml

* remove `continuous_deployment` env. var. - always set `scheduled: true` (it's ignored by OS Online anyway)
* add PROD values (even commented out) to job definition - so that we use it on PROD too
* much better docs

More consistent CD

---

README.md
openshift/imagestream-fedmsg.yml.j2
openshift/imagestream-worker.yml.j2
openshift/imagestream.yml.j2
playbooks/deploy.yml

to `false` on `prod` and `true` otherwise.
This doesn't change anything at the moment since these imports don't work on Online anyway.
But will be needed once we move elsewhere.

[Image streams] set 'importPolicy:scheduled' conditionally

---

playbooks/cleanup.yml

A variable evaluates just fine in a when-conditional, there is no need
for templating.
Removing this also fixes the following error:
```
The error was: error while evaluating conditional ({{ deployment }} !=
\"prod\"): 'dev' is undefined ...
```
when `DEPLOYMENT=dev`.

Remove jinja2 templating from when-conditional

---

openshift/redis.yml

Fixes #48
We don't need that many resources since
packit-service/packit-service#180

[Redis] new image & lower limits

---

openshift/redis-commander.yml
openshift/secret-redis-commander.yml.j2
playbooks/deploy.yml
secrets/template/extra-vars.yml

Also: enforce HTTPS for the web console.
redis Commander docs:
- https://github.com/joeferner/redis-commander/blob/master/docs/configuration.md#41-authentication-configuration-for-http-server
- https://github.com/joeferner/redis-commander#environment-variables

Enable HTTP authentication for redis Commander

---

openshift/imagestream-worker.yml.j2
openshift/imagestream.yml.j2
playbooks/deploy.yml
vars/template.yml

Before the image specs for packit-service and packit-service-worker were
composed of the image name and the tag, and the later was always
`deployment`.
This made somewhat difficult to deploy the service with *:prod images
locally.
This is made much simpler if we allow providing a full spec for these
images in `vars`.

Fully define images in vars

---

Makefile
README.md
playbooks/deploy.yml

This is to enable deploying Redis and/or Redis Commander on their own,
independent of the other objects in the OpenShift project.
One can use the `TAGS` env var to select tags to be run by `make
deploy`.
For example:
$ DEPLOYMENT=DEV TAGS="redis,redis-commander" make deploy
So far only "redis" and "redis-commander" are available as tags. `make
tags` can be used to tell all the tags available.
Furthermore: update Redis and Redis Commander related tasks to use
[`apply: yes`] for resource definitions, in order to make these
definitions idempotent. (Previously removing an environment variable
from the DeploymentConfig did not result in a DeploymentConfig change
because of the default merge_type used by k8s.) This requires Ansible
2.9 to run, but it's clearer then tweaking [merge_type]. …

Separate Redis and Redis Commander deployment

---

playbooks/deploy.yml

This task was tagged to be run for 'redis-commander' only, but extra
vars are needed by other tasks, too. So better always include them.

Always include extra secret vars

---

playbooks/get-certs.yml

'get-certs' related OpenShift objects are defined in a single file now.
Adjust the deployment task accordingly.

Update the get-certs playbook

---

secrets/template/packit-service.yaml

Will be valid only after packit-service/packit-service#561 is approved and merged.
- Adding `disable_sentry: True` to _secrets/packit-service.yaml_ disables sentry. 
- If this line is not present or `disable_sentry: False` is set then events will be sent to sentry like normal.

Optionally Disable Sentry

---

README.md
vars/template.yml

This is to transition the listener images to use the `stable` branch to build the image to be used in prod.
My idea was to finish up the CentOS listener pieces in the documentation once it's deployed to prod (currently it's only running in stage) - but let me know if I should add those, too.

Use `stable` branch for listener images

---

haxxx/job-import-images.yml
haxxx/validation/openshift/job-run-validation.yaml
openshift/flower.yml
openshift/packit-service-centosmsg.yml.j2
openshift/packit-service-fedmsg.yml.j2
openshift/redis-commander.yml
openshift/redis.yml

Services which need just few dozens Mi of mem were previously set to limit 128Mi.
After setting (#88) one of them to requests:32Mi & limits:64Mi, we were getting:
`spec.containers[0].resources.requests: Invalid value: '80Mi': must be less than or equal to memory limit`
When I'm trying to set requests to 64Mi or remove it completely the problem is still there,
so I think Openshift Online is set so that requests (& limits) can't be less than 80Mi.
EDIT: I'll test this on `stg` once I resolve a bug in `ansible-playbook` which prevents me from running `make deploy`.

Set resources:limits:memory: to 80Mi and remove resources:requests:

---

playbooks/deploy.yml
vars/template.yml

If you want to stay with docker, just put the following into `vars/dev.yml`:
```yaml
container_engine: "docker"
```
https://github.com/packit-service/packit-service/pull/669
Why?
I was wondering why when I run 'make check-inside-openshift' @ packit-service, my freshly added tests are not run - and, it's because the images are built with `podman` by default and pushed (some old images) with `docker`.

[playbooks/deploy.yml] push dev images with podman

---

.gitignore
README.md
playbooks/deploy.yml
vars/README.md
vars/dev_template.yml
vars/prod_template.yml
vars/stg_template.yml
vars/template.yml

In order to have shared settings for prod/stg deployment.
Previously a new team member (or someone who hasn't deployed to stg/prod yet) had to create their `{deployment}.yml` from `template.yml` while not sure what the settings should be for those deployments.
Now they can just copy for example `prod_template.yml` to `prod.yml` and only fill the token.
`{deployment}.yml` are still `.gitignore`d so they can't be pushed to git repo by mistake.

Store vars/{deployment}_template.yml 

---

openshift/secret-packit-secrets.yml.j2

They are not used
https://github.com/packit-service/dashboard/blob/master/files/cfg/httpd_packit.conf#L11

[packit-secrets] remove dashboard-*.pem

---

cron-jobs/import-images/Dockerfile
cron-jobs/validation/Dockerfile

Both were rebuilt and pushed to Docker Hub.

Upgrade cron job images to Fedora 32

---

scripts/setupcfg2rpm.py

Script setupcfg2rpm.py parses setup.cfg, extracts python packages from options->install_requires
section and wraps them into python3dist(package) so output can by used with dnf package installer.
Example:
$ dnf install $(setupcfg2rpm.py path_to_setupcfg)
python3dist(some_package)
python3dist(other_package)
$

Deploy script setupcfg2rpm.py

---

Makefile
README.md
containers/Dockerfile.base
cron-jobs/README.md
cron-jobs/rebuild-base-image/rebuild-base-image.yaml
docker/Dockerfile.base
openshift/secret-rebuild-base-image.yml.j2
playbooks/deploy.yml
playbooks/rebuild-base-image.yml

Base image build based on this configuration will contain the most generic
dependencies - only ansible rpm for now.
This PR contains:
* base Dockerfile
* OpenShift cronjob configuration
* secret with DockerHub webhook to trigger a build
* Makefile target to deploy it into OpenShift
* Documentation (+ small improvements to unrelated parts)

Create base image Dockerfile

---

playbooks/deploy.yml

Required only in `stg` deployment stage

Deploy base image configuration fix

---

cron-jobs/validation/packit-service-validation.py

After the namespace renaming `packit-service` -> `packit`, the Copr project name for hello-world PRs is different as well, so the script was trying to find the wrong Copr projects.

Rename Copr project name in validation script

---

openshift/packit-service-worker.yml.j2

To work-around source-git/kernel SRPM builds failing on
No space left on device
We now have 34Gi storage quota in total so
4(workers)*1Gi more shouldn't be a problem.

Workers now request 2Gi (was 1Gi) storage

---

openshift/tokman.yml.j2

I was trying to deploy tokman on stg and got error message with this configuration (`forbidden: minimum storage usage per PersistentVolumeClaim is 1Gi, but request is 256Mi`), so changed it to 1Gi

Change storage in volume for tokman to 1Gi

---

openshift/packit-service.yml.j2
openshift/tokman.yml.j2

- add `SENTRY_SECRET`, `DEPLOYMENT` vars to tokman env
- add `SENTRY_SECRET` var to packit-service env (packit/packit-service#784 - I see `configure_sentry()` is called also in service, but the env var is not set)

Add env vars to be able to run Sentry in tokman, p-s

---

roles/generate-secrets/templates/packit-service.yaml.j2
secrets/template/packit-service.yaml

https://github.com/packit/packit-service/pull/769 introduces a new variable (gitlab_token_secret) in config.

Adding gitlab_token_secret to packit-service.yaml

---

playbooks/deploy.yml

otherwise the block is not executed in case of:
`DEPLOYMENT=dev make deploy TAGS=packit-service-worker`

[playbooks/deploy.yml] Add tags to 'Push dev images'

---

playbooks/deploy.yml
vars/dev_template.yml

Up until now pushing the dev images depended on the name of the
deployment.
But this task was failing for deployments which were not done on a
cluster started with 'oc cluster up', but with 'minishift', for example.
Instead of relying on the name of the deployment to decide whether to
push the dev images, create a dedicated flag, to allow disabling this
task even when the deployment is done on an environment called 'dev' but
not on a cluster started with 'oc cluster up'.

Control pushing dev images with a dedicated flag

---

secrets/template/extra-vars.yml

If we had #68 we'd already know that [p-s uses the template](https://github.com/packit/packit-service/blob/master/files/deployment.yaml#L93) in `make check-inside-openshift`.

[secrets/template/extra-vars.yml] don't set aws keys

---

openshift/packit-service-worker.yml.j2

[SQS does not support broadcast](https://docs.celeryproject.org/en/latest/getting-started/brokers/index.html#broker-overview) and `celery status/inspect` results in `Error: Broadcast not supported by transport 'sqs'`

[worker] Run probes only if not using AWS SQS

---

openshift/packit-service-worker.yml.j2

- [we can't install celery from RPM](https://github.com/packit/packit-service/blob/master/files/install-deps-worker.yaml#L22)
- [we can't install pycurl from RPM](https://github.com/packit/packit-service/pull/823)
- [base image has to stay with Fedora-31](https://github.com/packit/packit-service/pull/822#issuecomment-696043755)
- [the probes don't work with SQS](https://github.com/packit/deployment/pull/135)
- [the readiness probe sometimes takes a looong time](https://github.com/packit/deployment/pull/135#issuecomment-691953962)
- Are they a reliable indicator of the workers health? Don't they actually tell us more about the broker's health?
I know it's a good practice to have the probes, but I have enough of trying to `pip install pycurl`, because we can't install it and celery with dnf …

Comment out worker probes

---

openshift/pushgateway.yml.j2
playbooks/deploy.yml

Since the [counter for Copr builds](https://github.com/packit/packit-service/pull/827) is rewritten with each push (so the value is always 1, see [metrics](https://workers.stg.packit.dev/metrics)) when using Pushgateway, I checked for similar issues and found [Prometheus Aggregation Gateway](https://github.com/weaveworks/prom-aggregation-gateway) which could better fit our use case. Tried it locally, it doesn't support the `persistence.file` and `persistence.interval` args, but otherwise worked well.

Use Prometheus Aggregation Gateway instead of Pushgateway

---

secrets/template/packit-service.yaml

This was added in https://github.com/packit/deployment/pull/77 due to https://github.com/packit/packit-service/pull/561 but 
reverted in https://github.com/packit/packit-service/pull/571
I need this because [marshmallow-3 now screams](https://github.com/packit/packit-service/pull/826) that it's unknown field.

[secrets/template/packit-service.yaml] remove disable_sentry

---

playbooks/deploy.yml

My https://github.com/packit/packit-service/pull/845 is waiting on dc/tokman rollout indefinitely.
Set the timeout to work-around this until I find out what's the problem.

[playbooks/deploy.yml] set timout for 'Wait for DCs rollouts' task

---

playbooks/deploy.yml
playbooks/tasks/set-facts.yml
playbooks/zuul-deploy.yml
vars/dev_template.yml
vars/prod_template.yml
vars/stg_template.yml
vars/template.yml

Since cb3d26a67 [deploy playbook is waiting also for tokman dc to rollout](https://github.com/packit/deployment/blob/master/playbooks/deploy.yml#L351).
This currently [breaks packit-service tests](https://github.com/packit/packit-service/pull/845) because tokman deployment rollout is not finishing - and I haven't been able to find out why yet.
So until I find out I need to make tokman optional.

Add with_tokman variable

---

.zuul.yaml
roles/generate-secrets/vars/main.yml

so that we don't have to set them for example in [.zuul.yaml](https://github.com/packit/deployment/blob/master/.zuul.yaml#L18)

[roles/generate-secrets/vars/main.yml] few sane default values

---

.pre-commit-config.yaml
playbooks/deploy.yml

In order to solve this installation issue:
https://github.com/prettier/prettier/issues/9459
It seems that prettier is moving the pre-commit parts in a separate
repository.

Update pre-commit configuration for prettier

---

cron-jobs/delete-pvcs/Makefile
cron-jobs/import-images/Makefile
playbooks/deploy.yml

[The clusters we use for dev/testing(Zuul)/stg/prod don't like images built & pushed with podman.](https://github.com/packit/deployment/issues/112#issuecomment-673343049)

Set CONTAINER_ENGINE/container_engine to docker

---

cron-jobs/validation/README.md
cron-jobs/validation/packit-service-validation.py

The new use cases:
- [commit (push) trigger](https://github.com/packit/hello-world/pull/158)
- [opened PR trigger](https://github.com/packit/hello-world/pull/159)
Improvements:
- remove the check of comment about the successful build (it will be removed in p-s)
- when checking that statuses are set to pending after triggering the build, when first status is set to pending, end (since it caused problems that we waited for all statuses and they could be e.g.outdated and not set)
TODO:

Add more use cases for validation script, improve checks

---

.gitignore
scripts/move_stable.py

Dependency: `click`
As a remote uses: `github.com:namespace/repo.git` (expects SSH key to be set up)
1. `scripts/move_stable.py init` creates a directory and clones all git repositories with stable branch into it (ran only once)
- resolves ambiguity of remotes `upstream` vs `origin` vs _any-other-creative-name_
- all repos have same prefix for their path
2. `scripts/move_stable.py move-all`
- runs git fetch
- prints out log from stable to master (there's also hash of stable in case of removing the confirmation before moving)
- automatically takes hash from master, but allows to input hash manually (I should add checking for invalid hash too)
- can be run from either the root of `deployment` or `scripts` directory (not interchangeable, `init` …

Add script for moving stable branches

---

vars/prod_template.yml

I recall we had set it to 3 back then when the build job was one big
task. This is no longer the case as the job was broke down to multiple
subtasks.
The longest task we have right now is the creation of an SRPM which for
packit e.g. takes ~2 minutes:
https://prod.packit.dev/srpm-build/12474/logs
Over the past few weeks I haven't seen a case where 3 SRPM builds were
running at the same time - I have no hard data though.
I feel like we can reduce the # of worker replica to 2 and save some
memory (it's even possible that 3 SRPM builds can't run at the same time
b/c of the timebound memory quota).
The worst case which can happen is that all workers would be busy with
SRPM builds and packit could be slow with setting initial statuses.

set prod worker replicas to 2

---

openshift/packit-worker.yml.j2

it's an increase by 128M
This change is done so we can clone bigger repos such as glibc or kernel-ark
source-git repos:
https://gitlab.com/packit-service/src/glibc.git
Sadly, one cannot verify this easily locally because there are multiple
processes in worker aside from just bash and git when trying this in a
container. Though I verified that glibc can be cloned with 256M and can't with
128M:
```
$ sudo podman run --rm -ti --memory 256mb docker.io/usercont/packit-worker:prod bash
bash-5.0# git clone https://gitlab.com/packit-service/src/glibc.git
Cloning into 'glibc'...
remote: Enumerating objects: 501438, done.
remote: Total 501438 (delta 0), reused 0 (delta 0), pack-reused 501438
Receiving objects: 100% (501438/501438), 200.76 MiB | 15.62 MiB/s, done.
Resolving deltas: 100% …
```

set worker memory to 512Mi

---

openshift/packit-worker.yml.j2

896 = 512 + 256 + 128
cloning repos is memory intensive: glibc needs 300M+, kernel 600M+
during cloning, we need to account for git and celery worker processes

worker memory: set to 896Mi

---

.github/workflows/base-image-rebuild.yml

so that the base image is rebuilt also when its Dockerfile changes.
Use organization level secrets instead of local repo secrets.

[.github/workflows/base-image-rebuild] run on push to main

---

cron-jobs/delete-pvcs/README.md
cron-jobs/delete-pvcs/delete-pvcs.sh

Previously we deleted only PVCs older than a day.
Now we delete all PVCs associated with pods in the Completed state.
EDIT: And also delete pods older than a day.
Fixes #192

delete-pvcs now deletes PVCs from any Completed pods

---

.github/workflows/base-image-rebuild.yml

This reverts commit 96629bc45540205460691499218d580cfcdb21a1.
The problem should be fixed with buildah-build v2.4.

Revert "Run workflow on ubuntu-18.04"

---

containers/Dockerfile.base

It makes the image bigger (+165MB), but having all packages updated is IMHO worth it.
We re-build the base image every Monday, so in case the update breaks anything, we have time till Friday to realize that, before we build prod images on top of it.

base image: run 'dnf update'

---

.pre-commit-config.yaml
cron-jobs/serve-acme-challenge.py
cron-jobs/validation/packit-service-validation.py
scripts/move_stable.py
scripts/setupcfg2rpm.py

So far the 'move_stable_repositories' directory was hard-coded throughout
the script. Add a --repo-store option to be able to customise this.
Also:
- use pathlib.Path everywhere to work with paths;
- improve help texts and validation of options and arguments;
- make repository and argument for move-repository, instead of an option
(it feels more natural);
- enable 'black' in the pre-commit config.

move-stable: Allow choosing a custom repo store

---

cron-jobs/validation/packit-service-validation.py

Since the PR object stores the head commit value, after the new commit push we get the statuses from the old head commit, therefore the PR object needs to be updated after the push.

[validation] update PR object after push

---

.pre-commit-config.yaml

* With ansible-lint pre-commit.ci does not work at all.
* We still have zuul to run the whole suite.

Skip ansible-lint in pre-commit.ci since it is too huge

---

cron-jobs/validation/packit-service-validation.py

This was a hotfix of https://sentry.io/organizations/red-hat-0p/issues/2421608064/?project=1767823&query=head_commit&statsPeriod=14d, so it's already updated in the image and running for over a week (just forgot to push the change).
When we do the test for opened PR trigger, the PR object is initialized later, therefore the `'NoneType' object has no attribute 'head_commit'`.

[validation] fix the head commit when there is no PR yet

---

cron-jobs/delete-pvcs/delete-pvcs.sh

I'm seeing some lingering pods (OOM Killed) & pvcs in prod deployment.
Related: #195, packit/packit-service#1047

delete-pvcs: Garbage collect also OOMKilled pods 

---

README.md
playbooks/check.yml
playbooks/deploy.yml
playbooks/tasks/project-dir.yml
playbooks/zuul-check.yml
playbooks/zuul-deploy.yml
roles/generate-secrets/tasks/main.yml
roles/generate-secrets/tasks/project-dir.yml
roles/generate-secrets/vars/main.yml

Previously it was a variable, redefined in the base job, but this no longer works.

Set project_dir as a fact

---

.gitignore
cron-jobs/validation/packit-service-validation.py

On Monday, the check runs should land in production, so this should be then merged and the image rebuilt, so that the script monitors check runs and not commit statuses.
I lowered some time limits, for submitting and completng of Copr build.

[validation] monitor check runs instead of commit statuses

---

openshift/packit-worker.yml.j2
openshift/sandcastle-volumes-for-cache.yml.j2
playbooks/deploy.yml
roles/generate-secrets/templates/packit-service.yaml.j2

Add persistent volume to the worker for repository-cache.
* The only option on OpenShift Online is AWS EBS provisioning
supporting only `ReadWriteOnce` access:
https://docs.openshift.com/online/pro/architecture/additional_concepts/storage.html#pv-restrictions  
Because of that, we need to have one repository-cache for each worker.
* The volume is mounted to /repository-cache path.
* For now, the content of the cache will be maintained (adding/updating) manually.

Add persistent volume for repository cache

---

containers/Dockerfile.base

because en_US locale is not actually available in the container base
image
>>> locale.setlocale(locale.LC_ALL, "C.UTF-8")
'C.UTF-8'
>>> locale.setlocale(locale.LC_ALL, "en_US.UTF-8")
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/usr/lib64/python3.9/locale.py", line 610, in setlocale
return _setlocale(category, locale)
locale.Error: unsupported locale setting
related: https://github.com/rebase-helper/rebase-helper/issues/867

base: set locale to C.UTF-8

---

cron-jobs/delete-pvcs/delete-pvcs.sh
cron-jobs/delete-pvcs/test.sh

The previous approach checked for stale pods first and deleted the
corresponding PVCs. But as we found out in the meantime, sometimes pods
are successfully removed, but the PVCs requested by them are not. These
PVCs would be never considered for deletion.
Change the approach to first delete stale pods, then identify all the
sandbox PVCs that are mounted in non-stale pods and then delete any
sandbox PVC that is not mounted.
Set up some basic testing.
Resolves #230.

Improve deleting stale sandbox PVCs

---

scripts/move_stable.py

Add command with GitHub query to move-stable script that prints out URL
with filter for pull requests with release notes that are included in
current change of stable branches.

Add command with GitHub query

---

containers/Dockerfile.base

Merge this after moving stable branches, i.e. either
- on Friday, so that the [base-image-rebuild workflow](https://github.com/packit/deployment/blob/main/.github/workflows/base-image-rebuild.yml) rebuilds it at 00:00 on Monday
- on Monday and re-run [the latest build](https://github.com/packit/deployment/actions/workflows/base-image-rebuild.yml) manually
after that, rebuild all `stg` images so that we have enough time to test before moving stable branches again.

Bump base image FROM fedora:33 -> 34

---

playbooks/deploy.yml
vars/stream/dev_template.yml
vars/stream/prod_template.yml
vars/stream/stg_template.yml

@TomasTomecek do you remember/know why we actually [set the finalizers to sandbox namespace](https://github.com/packit/deployment/blob/main/openshift/sandbox-namespace.yml.j2#L29)?

Setup sandbox namespace conditionaly

---

README.md
cron-jobs/import-images/job-import-images.yaml

We discussed on retro to move the stable branches on Monday, instead of
Friday, and release a new version of the service on Tuesday. This way if
something goes wrong we can take care of it during the week, without
ruining someones weekend.

Reschedule to import new images on Tuesday in Prod

---

openshift/packit-worker.yml.j2
playbooks/deploy.yml

Related to packit/packit-service#1184
(Don't merge and deploy until the tasks are reorganized)

Use repo cache only in workers serving long-running queue

---

openshift/packit-worker.yml.j2
playbooks/deploy.yml

Workers processing queues with short-running tasks require much less
memory than those which also process long-running tasks.

Make the memory limits of service-workers configurable

---

playbooks/deploy.yml
vars/packit/prod_template.yml

Jobs on some Cockpit repositories max out their time when building
SRPMs. This makes other repositories to wait longer for their SRPM
builds. Add a new worker to serve long-running tasks to improve on this
situation.

Configure deploying a long-running worker in prod

---

scripts/move_stable.py

Remove hardcoded day of moving stable branches in the script that
generates GitHub query for pull requests with ‹has-release-notes› label.

Remove hardcoded day of moving stable in warning

---

cron-jobs/packit-service-validation/README.md
cron-jobs/packit-service-validation/packit-service-validation.py

This way we can get rid of the "cannot have more than 100 pull requests
with the same head_sha" error.
Also: make it easier to run the validation script locally and improve the documentation.

validation: Delete the source branch after closing a new PR

---

cron-jobs/packit-service-validation/packit-service-validation.py

this was deprecated and removed from ogr already
Fixes https://sentry.io/organizations/red-hat-0p/issues/2793426268
Tests still running locally for me.

validation: use pr.comment instead of project.pr_comment

---

openshift/packit-worker.yml.j2
playbooks/deploy.yml

Similar to memory, short running workers don't need so much CPU.
Tested on stg.

Make the cpu limits of workers configurable

---

README.md

The link on certbot.eff.org was broken, and the new install instructions
recommend to use a snap version:
https://certbot.eff.org/instructions?ws=apache&os=fedora
Probably this is not needed as long as certbot is available from the
Fedora repositories. Remove these instructions in order to prevent
future readers from being confused.

certs: Tweak certbot install instructions

---

openshift/packit-worker.yml.j2

~`SERVICE` is really a bad name for this variable.
I chose it to distinguish between 'packit service' and 'stream service', but 'service' has so many meanings.
We are in a deployment repo and the variable basically specifies which project to deploy to - so `PROJECT` is much better.
It's used when playbooks are created from Jinja templates, so nothing needs to be re-deployed or changed anywhere else.~
EDIT: No renaming, see comments below. This PR just passes `project` (ansible) variable to worker as `PROJECT` to be utilized [here](https://github.com/packit/packit-service/blob/17e56e0fa9121aeca44afd27cf1dba973c0b21b5/packit_service/worker/database.py#L122).
---
N/A

Pass PROJECT into worker

---

openshift/github-app-private-key.yml.j2
openshift/secret-packit-config.yml.j2
openshift/secret-packit-secrets.yml.j2
openshift/secret-packit-ssh.yml.j2
openshift/secret-sentry.yml.j2
playbooks/deploy.yml

so that it really points the dir with secrets, not to the parent dir.
(Let's see what happens in Zuul ;-) )

Include {{ deployment }} in path_to_secrets

---

.ansible-lint
README.md
playbooks/check.yml
playbooks/deploy.yml
playbooks/tasks/check-up-to-date.yml
playbooks/tasks/set-facts.yml
playbooks/zuul-deploy.yml
vars/packit/dev_template.yml
vars/packit/prod_template.yml
vars/packit/stg_template.yml
vars/stream/dev_template.yml
vars/stream/prod_template.yml
vars/stream/stg_template.yml
vars/template.yml

When running a deployment, first check that:
- the deployment repository is up to date as compared to its remote;
- the secrets repository is up to date as compared to its remote;
- the deployment configuration is up to date compared to its template.

Check that the deployment resources are up to date

---

openshift/packit-service.yml.j2
openshift/packit-worker.yml.j2
playbooks/deploy.yml
vars/packit/prod_template.yml

Since 9f1186bed all pods have had [Guaranteed Quality of Service (QoS)](https://medium.com/google-cloud/quality-of-service-class-qos-in-kubernetes-bb76a89eb2c6).
But for workers (long-running and all-tasks) Burstable QoS is more appropriate because:
- most of the time they don't need so many resources, but under pressure, they need 2-4x more
- we would survive even if the system (k8s/Openshift) started killing them in case of running out of memory (unlikely to happen, but still)
EDIT: I was also thinking about doing the same for `packit-service` DeploymentConfig and increasing its memory limit to 2Gi, because that's the value we needed last time when doing alembic migrations.
It can be done because we don't have any quota now and we wouldn't need to increase it manually next (each) time …

Use Burstable instead of Guaranteed QoS for workers

---

scripts/changelog.py

2 changes:
```
changelog script: suffix items with #PR_ID
to have nice links in a release description
```
```
changelog script: support both release notes formats
v1 is `---`
v2 is the RELEASE NOTES section
this commit adds support for both
```
used to generate https://github.com/packit/packit/pull/1485

changelog script improvements

---

scripts/README.md
scripts/changelog.py

- fix of typo from the previous PR causing a traceback
- better handling of newlines
- ignoring of pre-commit autoupdate messages
- ref no longer needs to be specified, the last tag is used by default
- README describing how to use it

More improvements to changelog script

---

vars/packit/prod_template.yml

When the number of events from GitHub is high, the service is often
failing to give the initial feedback within 15 seconds.
Increase the number of workers handling short running tasks, in an
attempt to shorten response times.

Have 2 workers handle short running tasks

---

scripts/changelog.py

There was an inconsistency between actual implementation in `changelog.py` (option --git-dir) and the [docs](https://github.com/packit/deployment/tree/main/scripts) (option --git-repo).

Rename the option `--git-dir` to `--git-repo`

---

.zuul.yaml
openshift/secret-packit-config.yml.j2
scripts/gitlab_webhook.py
vars/fedora-source-git/prod_template.yml
vars/packit/prod_template.yml
vars/packit/stg_template.yml
vars/stream/prod_template.yml
vars/template.yml

There's no `stg_template.yml` because we don't have `stg` instance so far.

Add prod_template.yml var file for fedora-source-git

---

docs/continuous-deployment.md
openshift/packit-service.yml.j2

After [moving service to F35 & mod_wsgi-express](https://github.com/packit/packit-service/pull/1363) we were seeing some errors after the pod was running for some time.
As a workaround, we [restart the process(es) periodically](https://github.com/packit/packit-service/pull/1381), which helped on stg, but not on prod.
The culprit seems to be that now we need more memory. (Kudos to @TomasTomecek for spotting it.)
From metrics, the top was 247Mi so far, so I'm setting new requests/limits to 320Mi.
Note: I'll keep an eye on the metrics and merge this next week.

Give service more memory

---

openshift/postgres.yml.j2

In d9e8fb94 I set this to 20 because the default (100) looked like quite a lot in our case.
`SELECT count(*) FROM pg_stat_activity;` now shows over 20 (probably because of more workers?) so let's go back to the default.

Use default number of max connections

---

cron-jobs/delete-pvcs/job-delete-pvcs.yaml
cron-jobs/import-images/README.md
cron-jobs/import-images/job-import-images.yaml
cron-jobs/packit-service-validation/openshift/job-run-validation.yaml

`batch/v1` has been available since k8s v1.21 (Openshift 4.8)
`batch/v1beta1` will no longer be served in v1.25
https://kubernetes.io/docs/reference/using-api/deprecation-guide/#cronjob-v125

Move apiVersion: batch/v1beta1 to batch/v1 in cron jobs

---

scripts/changelog.py

Previously, the release note was taken from the last paragraph in the
merge commit. However, we then introduced the explicit release notes
marks (RELEASE NOTES BEGIN) and they've been in use for quite some time
already, new PRs (and releases) hence use only this format.
Removing the old style allows us to simply delete the release notes
marks from the PR if there is nothing worth mentioning in the changelog
(while also being able to add more information to the PR).

Drop support for old-style release notes

---

.gitignore
Makefile
README.md
docs/testing-changes.md
docs/tls-certs.md
playbooks/deploy.yml
playbooks/tasks/check-up-to-date.yml
scripts/download_secrets.sh
secrets/README.md
vars/packit/dev_template.yml
vars/packit/prod_template.yml
vars/packit/stg_template.yml
vars/stream/dev_template.yml
vars/stream/prod_template.yml
vars/stream/stg_template.yml
vars/template.yml

Add a `download-secrets` make target, which calls new `scripts/download-secrets.sh`, which:
- logins to Bitwarden and/or unlocks the vault
- downloads all files attached to `secrets-${SERVICE}-${DEPLOYMENT}` and `secrets-tls-certs` notes into `secrets/${SERVICE}/${DEPLOYMENT}/`
Example usage: `SERVICE=packit DEPLOYMENT=stg make deploy TAGS=secrets` downloads secrets into `secrets/packit/stg/` and re-deploys them into packit-stg.

Download secrets from Bitwarden vault

---

vars/packit/stg_template.yml

By removing the playbook variable,
we don't set it as env. var and value from service config is used (defaults to prod instance).

Use production distgit for packit-stg

---

containers/Dockerfile.base
scripts/setupcfg2rpm.py

Strip away comment if it is put with the dependency name.
Caused by packit/ogr#710

fix: ignore comments in script for python dependencies

---

scripts/changelog.py
scripts/move_stable.py

Example output (setting till=Monday) after fetching the repos (the next service guru will need to check that it actually works well after moving stable branches :-)):
```md
Here is a template for this week's blogpost (modifications may be needed)
- When initializing source-git repos, the author of downstream commits created from patch files which are not in a git-am format is set to the original author of the patch-file in dist-git, instead of using the locally configured Git author. ([packit#1575](https://github.com/packit/packit/pull/1575))
- Packit now correctly inform users about downstream errors only on the last try. (Previously, Packit informed for all tries even the last try succeded.) ([packit-service#1485](https://github.com/packit/packit-service/pull/1485))
```
Fixes: #317

Pre-generate blogpost from release notes

---

README.md
scripts/download_secrets.sh

And update the docs on what dependencies to install.
Replace the second `bw unlock --check` with a check for the
`BW_SESSION` environment variable, as I found `bw unlock --check`
reporting a locked vault, right after a vault was successfully unlocked.

Fix setting defaults in download_secrets.sh

---

scripts/move_stable.py

Dates are hard and I didn't read the manual properly when implementing it and noticed this when moving the stable branches :(

Fix off-by-one in move_stable

---

docs/allow-custom-copr-projects.md
scripts/update_bw_secret.sh
scripts/update_oc_secret.sh
secrets/README.md

Updating the `allowed_forge_projects_for_copr_project` config in `packit-service.yaml` is quite tedious.
This PR adds two scripts and some documentation to make this easier and consistent.

Improve the process to allow custom Copr projects

---

cron-jobs/packit-service-validation/packit-service-validation.py

The "Opened PR trigger" validation test is failing since the end of May,
b/c creating the new branch to test fails, as it already exists.
Update the test to delete the branch left over from the previous test
run.

validation: Delete the branch from the previous test run

---

playbooks/deploy.yml
playbooks/tasks/k8s.yml

Beside `notify` (https://github.com/packit/deployment/commit/492ccf419a5ff8d1da2b1901df71b16f1f37bd58) this is another use case when the [tasks/k8s.yml](https://github.com/packit/deployment/blob/main/playbooks/tasks/k8s.yml) can't be used.
The problem is that the loop item is ALWAYS evaluated even when the `when:` condition resolves to `False` (i.e. in this case when `with_flower` is `False`).
https://docs.ansible.com/ansible/latest/user_guide/playbooks_conditionals.html#loops-and-conditionals
When `with_flower` is `False`, the `htpasswd` file is not created in the previous task and the `secret-flower-htpasswd.yml.j2` template then fails to be processed.
```
2022-06-28 16:46:09.630911 | test-node | TASK [Upload flower secret] ****************************************************
2022-06-28 …
```

Don't use tasks/k8s.yml to deploy flower-htpasswd secret

---

vars/packit/prod_template.yml

Since we introduced workers for the specific (long/short running) queues, we've been adding specific workers but still kept the one common.
558771f3 -> 4d7c6550 -> aebd8375 -> c2554b01 -> cdf6beba
Now we've agreed that we actually don't need the common one.

Don't deploy a common worker on prod

---

containers/Dockerfile.base
secrets/template/packit-service.yaml

It was added in 3ae73fab9 because of [setupcfg2rpm script](https://github.com/packit/deployment/blob/main/scripts/setupcfg2rpm.py), but the script has not been used in packit-service since https://github.com/packit/packit-service/pull/1616#pullrequestreview-1075113194
It's used only in [tokman](https://github.com/packit/tokman/blob/main/Containerfile#L18) but that image is based on fedora (and not this base image).
The removal of `bugzilla_*` keys is related to packit/packit-service#1621

Remove python3-packaging from the base image

---

scripts/move_stable.py

We've installed ogr/specfile/packit from copr repos into packit-service images since packit/packit-service#1616 & packit/packit-service#1619 so before moving the packit-service stable branch (which triggers the images builds) we have to wait for the copr builds to finish (or rebuild the images later).

Move ogr&specfile first; warn user to wait for builds

---

scripts/changelog.py
scripts/move_stable.py

So that the formatting is preserved. GitHub strips Markdown in merge commits.
Co-authored-by: Laura Barcziová <lbarczio@redhat.com>
Co-authored-by: Nikola Forró <nforro@redhat.com>
Co-authored-by: František Lachman <flachman@redhat.com>
Co-authored-by: Maja Massarini <mmassari@redhat.com>
Co-authored-by: Matěj Focko <mfocko@redhat.com>
Co-authored-by: Tomáš Tomeček <ttomecek@redhat.com>

changelog.py: get release notes from GitHub PRs

---

README.md
docs/logs.md
openshift/packit-worker.yml.j2
openshift/secret-splunk.yml.j2
playbooks/deploy.yml
vars/fedora-source-git/prod_template.yml
vars/fedora-source-git/stg_template.yml
vars/packit/prod_template.yml
vars/packit/stg_template.yml
vars/stream/prod_template.yml
vars/stream/stg_template.yml
vars/template.yml

https://github.com/packit/research/pull/152
We use our image https://quay.io/repository/packit/fluentd-splunk-hec, built via [a GitHub workflow](https://github.com/jpopelka/fluent-plugin-splunk-hec/blob/main/.github/workflows/rebuild-and-push-image.yml) because we don't want to use [docker.io/splunk/fluentd-hec image](https://hub.docker.com/r/splunk/fluentd-hec).
I've been unsuccessful in sending data to Splunk HEC so far.
This is a middle step to make sure the fluentd sidecar works OK and at this moment we're [sending logs to files](https://docs.fluentd.org/output/file) in a persistent volume mount to `/var/log/packit/` in the fluentd container.
Once a day is the intermediate `buffer.*.log` file in `/var/log/packit/` flushed and compressed into a permanent gzip file.
The file is `.` …

Add fluentd sidecar to worker

---

Makefile
docs/allow-custom-copr-projects.md
playbooks/render_secrets_from_templates.yml
scripts/render_secrets_from_templates.sh
scripts/update_bw_secret.sh
secrets/README.md

You need it if you want to create `packit-service.yaml` in order to run
`$ scripts/update_oc_secret.sh packit-config secrets/packit/stg/packit-service.yaml`
I've been thinking about whether to call it directly after downloading the secrets from the vault, but I'm leaving it separated so that people are aware that it's generated and not downloaded from the vault.
Also, it's not needed during the deployment so it'd slow it down.

Add `render-secrets-from-templates` target

---

Makefile
secrets/README.md

So that Bitwarden CLI can use older algorithms.
Resolves #329.

Disable OpenSSL system configs when downloading secrets

---

openshift/packit-worker.yml.j2
vars/packit/prod_template.yml

kinda reverts 7b074a7ae but don't specify `POOL` because of packit/packit-service#1770
I'll merge next week once packit/packit-service#1770 is in stable/prod.

One 16-threaded short-running worker @ prod

---

openshift/dashboard.yml.j2
openshift/flower.yml
openshift/nginx.yml.j2
openshift/packit-service-beat.yml.j2
openshift/packit-service-fedmsg.yml.j2
openshift/packit-service.yml.j2
openshift/pushgateway.yml.j2
openshift/redis-commander.yml
openshift/redis.yml
openshift/tokman.yml.j2
playbooks/deploy.yml

Looking at packit prod resource utilization graphs, one can see that we're requesting 1.4cpu, but utilizing 0.1-0.4cpu, so we're too greedy.
I went through packit-prod metrics for individual components for the past 2 weeks and adjusted the resource limits to be 2-3x the values at peaks so we should still be safe.
You can see that it's mostly adjusting cpu, but in some cases, it decreases the memory limit from 80Mi to 32Mi.
Those are components that need only a few MiB of memory but previously had the limit set to 80Mi because of Openshift Online where the limit couldn't be less than 80Mi, see 746cf271692
I already deployed this to `packit-stg` so you can check that everything works as expected.

Adjust resource limits based on prod metrics

---

.github/workflows/base-image-rebuild.yml
.github/workflows/build-and-push-cronjob-image.yml

Related to #396
* https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
* https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter

Use environment files instead of set-output command

---

playbooks/import-images.yml

When running `make import-images`, we were missing a fluentd sidecar image, so let's add it to the playbook :)

fix(import): add fluentd sidecar to image streams

---

openshift/packit-worker.yml.j2

I initially didn't give (becf1012ae) the container any resource limits because with them it takes the container some time to start.
But we need them so that the pod is not in the `BestEffort` QoS class.
With requests set to 10m and limits to 100m we're in the `Burstable` class and `fluentd` starts a few seconds after the worker so it doesn't miss that much.

Add resource requests & limits to fluentd sidecar

---

docs/continuous-deployment.md
openshift/dashboard.yml.j2
openshift/flower.yml
openshift/nginx.yml.j2
openshift/packit-service-beat.yml.j2
openshift/packit-service-fedmsg.yml.j2
openshift/packit-service.yml.j2
openshift/packit-worker.yml.j2
openshift/postgres.yml.j2
openshift/pushgateway.yml.j2
openshift/redis-commander.yml
openshift/redis.yml
openshift/tokman.yml.j2
playbooks/deploy.yml

OpenShift introduced `DeploymentConfig` objects before `Deployments` were added to upstream Kubernetes.
[Deployments are now in general preferred in OCP 4](https://docs.openshift.com/container-platform/4.11/applications/deployments/what-deployments-are.html#deployments-comparing-deploymentconfigs_what-deployments-are).
For me personally, the benefit would be that:
- I could see Metrics for the Deployment without having to go to Pods first
- the *-deploy pods would no longer (as I understand it) clutter the list of all (project's) pods

Use Deployments instead of DeploymentConfigs

---

openshift/dashboard.yml.j2
openshift/flower.yml
openshift/nginx.yml.j2
openshift/packit-service-beat.yml.j2
openshift/packit-service-fedmsg.yml.j2
openshift/postgres.yml.j2
openshift/pushgateway.yml.j2
openshift/tokman.yml.j2
playbooks/deploy.yml

Use Burstable QoS for more/most pods, not just workers (d9278288).
Guaranteed QoS (when requests == limits) is the 'best' class, but you
have to carefully set the values (the same for requests and limits) so that
- it's enough for all use cases, but at the same time
- it's not too much because you'd waste the reserved (requested) resources.
And you actually don't need the generic workloads to be 'guaranteed'.
The Guaranteed QoS makes sense for the 'sensitive' workloads, like in
our case postgres and redis (maybe the service/api).
With the Burstable QoS (requests < limits) we can set
- requests to what the pod needs most of the time
- limits to some high value (more than what the pod needs in spikes)
to have a safety net when a pod gets crazy
- when it becomes a memory hog due to a memory …

Yet another update of resource requests & limits

---

scripts/move_stable.py

When there are no Copr dependencies to wait for, current implementation did:
Waiting for Copr builds [------------------------------------] 0%
Switch it, so that for no dependencies it just prints out an information about no dependencies being configured.

fix(scripts,stable): disable progress bar for no deps

---

openshift/packit-service.yml.j2
openshift/packit-worker.yml.j2

The `default_ccache_name = KEYRING:persistent:%{uid}` from `/etc/krb5.conf` didn't work for us after OpenShift 4.10->4.11 upgrade. We were getting `kinit: Function not implemented while getting default ccache`.
Kudos to @lachmanfrantisek

Set kerberos credentials/ticket cache location

---

playbooks/deploy.yml
vars/packit/prod_template.yml
vars/packit/stg_template.yml

4Gi for both prod and stg should be enough given that all worker pods say:
```
$ du -h /repository-cache/
20K     /repository-cache/
```
Until packit/packit-service#1840 is fixed.

Smaller repository_cache_storage

---

openshift/postgres.yml.j2

When I temporarily raised the mem limit to 2Gi on packit-prod a week ago the db became A LOT more responsive, (probably because the `shared_buffers` and `effective_cache_size` are set automatically based on the mem limit, see 2f07b23 commit message) while the total mem consumption stayed pretty much the same (maybe even a bit lower).
We can either play again (2f07b23) with setting the buffers & cache to higher values while keeping the pod in Guaranteed QoS (requests == limits). Or simply increase the limit permanently, which would change the QoS from Guaranteed to Burstable (limits > requests). I decided for the latter (see 3b0d20e for more info).

Burstable QoS for postgres

---

Makefile
scripts/download_secrets.sh
secrets/README.md

The issues for which this was a workaround seems to be fixed in Bitwarden CLI v2023.1.0: https://github.com/bitwarden/clients/releases/tag/cli-v2023.1.0

Revert unsetting OPENSSL_CONF

---

openshift/packit-worker.yml.j2
playbooks/deploy.yml

```
$ celery -A packit_service.worker.tasks status
->  celery@packit-worker-long-running-1: OK
->  celery@packit-worker-short-running-0: OK
2 nodes online.
```
The command usually takes about 7s to finish but can go up to 20-30s so the timeout is set to 1min to be on the safe side and not restart a worker needlessly.
There is no readiness probe because it IMHO makes no sense for pods with no inbound traffic.
We already had the probes a long time ago, but we removed them (94cee4a03) because they hadn't worked as expected.
Let's give it another try.
Related to packit/packit-service#1858

Workers: add liveness probe

---

secrets/fedora-source-git/prod/packit-service.yaml.j2
secrets/fedora-source-git/stg/packit-service.yaml.j2
secrets/stream/prod/packit-service.yaml.j2
secrets/stream/stg/packit-service.yaml.j2

This is going to be needed once packit/packit#1846 and packit/packit-service#1921 is merged.

Configure the source-git services to override the package config path

---

openshift/tokman.yml.j2
playbooks/deploy.yml
vars/packit/prod_template.yml

Tokman had issues keeping up with the load on prod, which manifested in the liveness and readiness probes failing quite often, and occasionally ridiculous response times.
Using 2 gunicorn workers somewhat improves the situation, but that requires more resources. Update the playbook and the vars file for packit-prod accordingly.
Also change from using a readinessProbe to using a startupProbe. For tokman being ready and being live is the same: a response is received in a timely manner on /api/health. But we don't want to run the liveness probe before the startup has completed (the alembic migration completed and gunicorn started). Use the startup probe to check this. This will run only once, trying a few times, and stopping once successful. It might be that this was the intention with the …

Tweak tokman resources and the number of workers

---

playbooks/deploy.yml

Workers running both queues should get at least as much resources as workers handling only long running tasks.

Get more resources for workers running both queues

---

openshift/dashboard.yml.j2
openshift/packit-service-beat.yml.j2
openshift/packit-service.yml.j2
openshift/postgres.yml.j2

it's been quite hungry since packit/packit-service#1787
and tune CPU requests of some workloads (they should still be enough in (almost) all cases)

Double Postgresql memory requests & limits

---

openshift/packit-worker.yml.j2

We need to be much less aggressive because the probe is still failing from time to time.
packit/packit-service#1928 should also help with the problem
(This is the same as #457, I just can't reopen it because the branch was force-pushed)

Increase liveness probe values

---

vars/packit/prod_template.yml

It turns out, that having 2 workers running in parallel will lead to a race condition, and there will be times when there are multiple tokens requested for the same repo. Avoid this, by dropping the number of workers to 1. Adjust resources accordingly.
Related to packit/tokman#53.

tokman: reduce the number of workers and resources in packit prod

---

.zuul.yaml
playbooks/deploy.yml
playbooks/zuul-deploy.yml

This reverts commit 71f67c0 done after the tests had mysteriously started to fail (on images being pulled to image streams)
So, I'm just checking (again :) ) whether it perhaps hasn't solved itself meanwhile :)
since we have a new major Zuul version deployed.

Revert "Disable deployment-tests until we fix them"

---

cron-jobs/packit-service-validation/packit-service-validation.py

Validation script for:
- gitlab.gnome.org
- gitlab.freedesktop.org
- salsa.debian.org
Merge before: packit/helm#23

Add validation in other gitlab instances

---

cron-jobs/packit-service-validation/packit-service-validation.py

In `gitlab.com` and `gitlab.freedesktop.org` we have a group as namespace -> `packit-service`
In `salsa.debian.org` and `gitlab.gnorme.org` we have the user namespace -> `packit-validation`

Fix namespace for validation project in freedesktop

---

openshift/postgres.yml.j2

It's not `1Gi` (my mistake ace51c0) but `1` and it can be the same for prod and stg (since it's the limit, not the requests).

Fix cpu limit for postgres

---

containers/Containerfile.c9s

With switch to MP+ we have also switched from PostgreSQL 13 to 15, this becomes an issue, since by default the C9S includes version 13 and regular backup is done from the worker.
Since we have multiple worker images, enable the ‹postgresql› module globally to reduce unnecessary copy-pasta into the playbooks for building workers.
Fixes #514

fix(c9s): enable postgresql module

---

secrets/packit/prod/packit-service.yaml.j2
secrets/packit/stg/packit-service.yaml.j2

Making ‹pass.redhat.com/appcode› and storage class for requested PVCs for sandcastle customizable.
Related to packit/sandcastle#190

fix(mpp): add appcode and sandcastle's storage class

---

scripts/move_stable.py

Current date is not reliable and the file/link is better to be tight to the week number.

Create weekly post file in the $YEAR directory

---

openshift/packit-service.yml.j2

We agreed on increasing it permanently to avoid problems with database migrations.

Increase memory limit for packit-service to 4Gi

---

playbooks/check.yml
playbooks/deploy.yml
playbooks/render_secrets_from_templates.yml
playbooks/tasks/set-deployment-facts.yml
playbooks/tasks/set-facts.yml

To enable including them only in deployment, and therefore allow rendering of templates where we don't need to have all of the ansible facts related to deployment.

fix: factor out deployment facts

---

scripts/move_stable.py

When updating the references to the ‹stable›, we need to pull the changes done by the others first.

fix(move-stable): pull the monorepo changes first

---

secrets/fedora-source-git/prod/fedora.toml.j2
secrets/fedora-source-git/stg/fedora.toml.j2
secrets/packit/prod/fedora.toml.j2
secrets/packit/stg/fedora.toml.j2

Related to packit/packit-service#2068

Subscribe to Anitya messages

---

scripts/move_stable.py

Issues fixed:
- naming conflict of variable and function
- pulling of changes from remote when updating only one submodule

Fix updating of monorepo references for one repo

---

secrets/packit/stg/packit-service.yaml.j2

As it was suggested by @thrix (@mvadkert), we should use staging API of Testing Farm on our staging instance to test and validate their changes.
Given the fact there are not many users of Packit staging instance apart from Packit Team and Packit Validation, we should be able to verify the TF changes before they land on **both** TF and Packit production, which should in turn increase overall stability of Testing Farm experience while using Packit.

feat: use staging TF API on stage

---

secrets/packit/prod/packit-service.yaml.j2

fix: switch TF API URL to the production API endpoint

---

docs/deployment/logs.md
openshift/dashboard.yml.j2
openshift/nginx.yml.j2
openshift/pushgateway.yml.j2
playbooks/deploy.yml
playbooks/import-images.yml
secrets/packit/prod/packit-service.yaml.j2
vars/fedora-source-git/prod_template.yml
vars/packit/prod_template.yml
vars/packit/stg_template.yml
vars/template.yml

Rebased on top of @majamassarini PR, so it's easy to retry next time.

Mpp prod move

---

openshift/redis.yml.j2

As suggested by @jpopelka in #555, there's also a new redis image of version 7 being present.
Scaled down workers before bumping the image, looks like it went without any hiccups

chore: bump redis from 6 to 7

---

containers/Containerfile.c9s

As the cache of the postgresql:15 builds expired, we ran into some issues with regards to the service builds that depend on postgresql for the ‹pg_dump›. Since 16 is not affected by this issue, bump the module for now and revert later once psql:15 is available again.

fix: bump postgres in the base image

---

openshift/packit-service.yml.j2
openshift/postgres.yml.j2
vars/packit/prod_template.yml

After switching our deployment to MP+ we (read as “me”) missed some occurences of hardcoded project/namespace for Packit Service deployment.
* Fix those typos.
* Add warning to the template.

fix: fix typos in the exceptions for limits

---

openshift/nginx.yml.j2

Use nginx image from quay.io instead of ghcr.io, since it doesn't get “rate-limited”.

fix(imagestream): use quay.io images for nginx

---

openshift/packit-service.yml.j2
openshift/postgres.yml.j2

By default shm size is 64MB, *dashboard usage* page uses around 100MB.
I can reproduce the error described in packit/packit-service#2385 locally using podman compose and I can fix it by setting `shm_size: 128Mi` in `docker-compose.yml`.
I tried deploying these openshift changes on my local openshift cluster but even though the new volume is created and mapped the size didn't change.
`df -h /dev/shm` is always 64MB
I would like to test this on stg, to be sure the problem is not related with my local openshift cluster.
But, as far as I can understand it, does exist a `SizeMemoryBackedVolumes` k8s *feature gate*, which is not enabled in the cluster by default (probably because this is a  dangerous feature https://github.com/kubernetes/kubernetes/issues/119611).
If this is not enabled in the …

Customize shm size in postgres pod

---

scripts/render_secrets_from_templates.sh

When rendering the secrets, e.g., config template, via script, we run some parts of the playbooks that may depend on the variables for a deployment (like MP+ vs Automotive, and such). Warn about this fact to make sure there are no discrepancies introduced by outdated “secrets”.

fix(scripts): warn about the vars dependency

---

playbooks/deploy.yml

The previous cpu limit increase 7b88605f16ee5a7f52ad06bef4d462eab940d645 should be enough.
The cluster running our pods should have enough resources to satisfy our needs without us blocking the resources.

Lower cpu requests

---

openshift/dashboard.yml.j2

Related to packit/dashboard#410

Expose Sentry related env var in dashboard pod

---

openshift/packit-worker.yml.j2

Add the configuration needed for OpenScanHub integration and adjust the packit-config volume so that the config is being mounted in the subdirectory along the existing secrets.
Followup of packit/packit-service#2463
This now runs on staging and works.

Adjust packit-config volume in packit-worker

---

openshift/packit-service.yml.j2
openshift/packit-worker.yml.j2
openshift/secret-centpkg-sig.yml.j2
playbooks/deploy.yml
playbooks/render_secrets_from_templates.yml
secrets/packit/prod/centpkg-sig.conf.j2
secrets/packit/stg/centpkg-sig.conf.j2

Override the default config, since we are going to require the usage of GitLab.com for more streamlined experience across both CentOS Stream and CentOS SIGs.
Fixes packit/packit#2305

feat(centpkg-sig): override the default config

---

secrets/packit/prod/packit-service.yaml.j2
secrets/packit/stg/packit-service.yaml.j2

Follow up of packit/packit#2408
RELEASE NOTES BEGIN
N/A
RELEASE NOTES END

Configure default_parse_time_macros for packit-service

---

scripts/move_stable.py

1. Remove tokman as it is no longer deployed.
2. Remove hardly as it is no longer deployed either.

fix(move-stable): remove archived repos

---

docs/deployment/specifics/clusters.md

docs(mpp): document MP+ specifics and firewall rules

---

playbooks/deploy.yml
playbooks/roles/deploy/defaults/main.yml
playbooks/roles/deploy/tasks/main.yml

• Summary
Initially I wanted to do ‹k8s_apply=false› for postgres, and key-value
databases (such as Redis, Redict, or Valkey), because deploying on prod
with ‹k8s_apply=true› caused redeployment of the postgres which caused
a small outage (~5 minutes).
Right now when I tried to redeploy stage multiple times in a row, none of
the deployed services got redeployed, hence I come to the conclusion that
there were some changes on the production deployment that were applied
back then.
• Context from https://github.com/packit/deployment/issues/360
· What it actually does?
In the simple terms, it makes sure that the definition that is to be
deployed matches the one that is already deployed. The difference has
already manifested few times, e.g., when @majamassarini was adjusting
the `/dev/shm` for …

chore: use k8s_apply=true by default

---

openshift/postgres.yml.j2

Also resized the stage for the testing purposes, it ain't much(, but it's an honest work), if we reserve a lot of resources on preprod, we can relax it (we're using barely 300MB on stage).
Turns out that you, indeed, can resize the PVC with the pod running and then just rescale the deployment (postgres).
Fixes #604

chore(postgres): enlarge the postgres volume

---

secrets/packit/prod/packit-service.yaml.j2
secrets/packit/stg/packit-service.yaml.j2

We need to run internal TF jobs on the https://github.com/rhel-lightspeed/command-line-assistant project.

Allow github.com/rhel-lightspeed/command-line-assistant to use internal TF

---

playbooks/deploy.yml
playbooks/roles/deploy/tasks/main.yml

I am monitoring the hard time limits exceptions since a while, seems like that when we have spikes both in the short running workers and in the long running we sometimes get an hard time limit exception for the celery tasks.
We have spike above the requested limits (as you can see in the today picture) mainly for the short running workers.
We have exceptions for the spikes even when the single worker cpu usage is below the `limits_cpu` and I am wondering if this limit applies to the sum of all our replicas or just for the single replica?
**I would say it is the limit for all the replicas together and in this case we need to increase much more the `limits_cpu` both for the long running and the short running pods (I would put there 1G of `limits_cpu` for both kind of workers in this …

Increase limits_cpu for the short_running_workers

---

.github/workflows/base-image-rebuild.yml

fix(base): install QEMU for ‹RUN› in build action

---

.github/workflows/base-image-rebuild.yml
containers/Containerfile

Related to https://github.com/packit/deployment/issues/613.

Switch base image to Fedora 41

---

.github/workflows/base-image-rebuild.yml

I don't know what's wrong, it looks like OpenSSL on Fedora 41 ppc64le doesn't support SHA384 (but I'm not able to reproduce it outside of Github Actions environment):
```bash
$ openssl s_client -servername mirrors.fedoraproject.org -connect mirrors.fedoraproject.org:443 < /dev/null
Connecting to 140.211.169.196
depth=2 C=US, O=DigiCert Inc, OU=www.digicert.com, CN=DigiCert Global Root G3
verify return:1
depth=1 C=US, O=DigiCert Inc, CN=DigiCert Global G3 TLS ECC SHA384 2020 CA1
verify error:num=7:certificate signature failure
verify return:1
depth=1 C=US, O=DigiCert Inc, CN=DigiCert Global G3 TLS ECC SHA384 2020 CA1
verify return:1
depth=0 C=US, ST=North Carolina, L=Raleigh, O=Red Hat, Inc., CN=*.fedoraproject.org
verify error:num=7:certificate signature failure
verify return:1
depth=0 …
```

Fix base image build

---

roles/deploy/tasks/main.yml

I did't touch requests because when idle our workers consume even less than this.

Increase cpu limit to handle spikes better

---

roles/deploy/tasks/main.yml

We can't assign more than 2cpu to a single pod.

Set cpu limit to 2

---

openshift/dashboard.yml.j2
openshift/flower.yml.j2
openshift/nginx.yml.j2
openshift/packit-service-beat.yml.j2
openshift/packit-service-fedmsg.yml.j2
openshift/packit-service.yml.j2
openshift/packit-worker.yml.j2
openshift/postgres.yml.j2
openshift/pushgateway.yml.j2
openshift/redict.yml.j2
openshift/redis-commander.yml.j2
openshift/redis.yml.j2
openshift/valkey.yml.j2
playbooks/deploy.yml
roles/deploy/defaults/main.yml
roles/deploy/tasks/main.yml
vars/packit/prod_template.yml

We are hitting several cpu limits and weird packit-service behaviour with it. Many resources on internet suggest not to use cpu limits (but instead adjust cpu requests if needed),
like this one:
https://medium.com/inside-sumup/are-kubernetes-cpu-limits-bad-a04430bf54e1

Remove cpu limits

---

openshift/dashboard.yml.j2
openshift/flower.yml.j2
openshift/nginx.yml.j2
openshift/packit-service-beat.yml.j2
openshift/packit-service-fedmsg.yml.j2
openshift/packit-service.yml.j2
openshift/packit-worker.yml.j2
openshift/postgres.yml.j2
openshift/pushgateway.yml.j2
openshift/redict.yml.j2
openshift/redis-commander.yml.j2
openshift/redis.yml.j2
openshift/valkey.yml.j2
playbooks/deploy.yml
roles/deploy/defaults/main.yml
roles/deploy/tasks/main.yml
tasks/check-up-to-date.yml
vars/packit/dev_template.yml
vars/packit/prod_template.yml
vars/packit/stg_template.yml

If we don't set cpu limits they are being set by default (500m) but this value is too low for some of our pods.
Keep cpu limits.
Increase postgres cpu limit.

Increase cpu limits for postgres

---

.ansible-lint
playbooks/test_deploy.yml
playbooks/test_deploy_setup.yml
roles/deploy/tasks/main.yml

After the last memory increase, it seems the workers are using more cpu and executing much more tasks. So memory seems to be a real bottleneck.

Increase short running worker memory

---

secrets/packit/stg/packit-service.yaml.j2

Here are a few packages that I maintain with various levels of permissions `commit`, `collaborator`, `admin`, `maintainer`. I guess the way to test it will be to open a bump PR and see if the `scratch-build` and `testing-farm` workflow work?

Add fedora-ci for packages maintained by lecris

---

openshift/configmap-redis_like_config.yml

This is a timeout after which idle connections are closed. I would try to lower it to 10 mins instead of 30 and see if it helps with downtime for the issue of idle workers (packit/packit-service#2697).

Lower the timeout in redis-like config

---

secrets/packit/prod/packit-service.yaml.j2
secrets/packit/stg/packit-service.yaml.j2

We need to enable tests in Image Mode for `fido-device-onboard-rs` upstream project.
In order to do so, we need to be able to use RHEL-10 as target in Packit configuration of the repository.

Allow github.com/fdo-rs/fido-device-onboard-rs to use internal TF

---

.envrc
.gitignore
devenv.lock
devenv.nix
devenv.yaml
docs/deployment/continuous-deployment.md
docs/deployment/nix.md
docs/deployment/resource-requirements.md
docs/deployment/specifics/packit-service.md
docs/deployment/specifics/redict.md
scripts/download_secrets.sh
scripts/render_secrets_from_templates.sh
scripts/update_bw_secret.sh
scripts/update_oc_secret.sh

nix-shell support and fix shebangs

---

devenv.nix
docs/deployment/tls-certs.md

Adjustments from TLS certs renewal
