packit/deployment

- README.md
- openshift/deployment-fedmsg.yml.j2
- openshift/deployment-worker.yml.j2
- openshift/deployment.yml.j2
- playbooks/deploy.yml
- vars/template.yml
needs https://github.com/packit-service/packit-service/pull/107
> worker: RollingUpdate, readinessProbe and volumeClaimTemplates

- Makefile
- openshift/deployment-worker.yml.j2
- playbooks/cleanup.yml
- playbooks/deploy.yml
- vars/template.yml
https://github.com/packit-service/packit-service/pull/104
> Use separate worker image

- Makefile
- README.md
- playbooks/zuul-secrets.yml
- secrets/template/packit-service.yaml
Please do not merge until it is verified that it works here: https://github.com/packit-service/packit-service/pull/88.
> playbook for zuul secrets encryption

- README.md
> [README] worker:prod rebuild is not triggered automatically on packit:prod rebuild

- README.md
See https://github.com/packit-service/deployment/pull/12#pullrequestreview-291124451
> [README] No need to copy cert.pem & chain.pem

- openshift/deployment.yml.j2
Needs to be merged together with https://github.com/packit-service/packit-service/pull/147
> [openshift/deployment.yml.j2] change command

- secrets/template/packit-service.yaml
- Update structure of the config file template.
> Update config template structure

- openshift/deployment-worker.yml.j2
- openshift/secret-sentry.yml.j2
- playbooks/deploy.yml
also:
```
remove req on ansible 2.7
ansible-2.8.5-1.fc30.noarch works well for me
```
> add sentry secret

- Makefile
- playbooks/acme.yml
- playbooks/cleanup.yml
- playbooks/deploy.yml
- playbooks/get-certs.yml
- playbooks/zuul-secrets.yml
- vars/template.yml
ansible-2.8.5-1.fc30.noarch works well for me
> require ansible >= 2.8

- playbooks/deploy.yml
didn't try it though, should just work™
> deploy: make it work with ansible 2.7 & 2.8

- secrets/template/fedora.toml
Needed for E2E tests for packit-service.
> add example fedora.toml config

- vars/template.yml
> [vars/template] remove unused deployment_image

- openshift/deployment-fedmsg.yml.j2
- playbooks/deploy.yml
- vars/template.yml
https://github.com/packit-service/packit-service/pull/240
> Fedora messaging consumer has separate image now

- Makefile
- README.md
- haxxx/Dockerfile
- haxxx/README.md
- haxxx/import-images.sh
- haxxx/job-import-images.yml
- openshift/deployment-fedmsg.yml.j2
- openshift/deployment.yml.j2
- openshift/imagestream-fedmsg.yml.j2
- openshift/imagestream-worker.yml.j2
- openshift/imagestream.yml.j2
- openshift/statefulset-worker.yml.j2
- playbooks/deploy.yml
- playbooks/import-images.yml
- vars/template.yml
Fixes #30
https://blog.openshift.com/image-streams-faq
> Add ConfigChange & ImageChange triggers

- openshift/pg.yml
- openshift/secret-postgres.yml.j2
- playbooks/deploy.yml
- secrets/template/packit-service.yaml
> add postgresql

- secrets/README.md
- secrets/template/extra-vars.yml
> Add secrets/template/extra-vars.yml

- openshift/deployment.yml.j2
- openshift/pg.yml
- openshift/statefulset-worker.yml.j2
* fix selectors
* add env vars how to conn to pg for service and worker
> fix pg deployment:

- openshift/flower.yml
- openshift/secret-flower.yml.j2
- playbooks/deploy.yml
- secrets/template/extra-vars.yml
> Enable Basic Authentication for Flower

- Makefile
- playbooks/deploy.yml
Also contains:
* pre-commit fixes
* deploy.yml: add description to the token block
* wait for worker to be deployed for 10 minutes
This is needed in p-s' CI testing and for local development.
> push dev images to openshift's registry if needed

- README.md
- openshift/packit-service-centosmsg.yml.j2
- openshift/secret-centos-secrets.yml.j2
- playbooks/deploy.yml
- vars/template.yml
tested - pod is running in stg environment
> added centos_msg pod config

- secrets/template/packit-service.yaml
See https://github.com/packit-service/packit-service/issues/552
> [secrets/template/packit-service.yaml] remove fedora-messaging keys

- Makefile
- README.md
- playbooks/generate-local-secrets.yml
- roles/generate-secrets/tasks/check-github-key.yml
- roles/generate-secrets/tasks/create-directories.yml
- roles/generate-secrets/tasks/generate-cert.yml
- roles/generate-secrets/tasks/generate-copr-config.yml
- roles/generate-secrets/tasks/generate-fedora-config.yml
- roles/generate-secrets/tasks/generate-packit-config.yml
- roles/generate-secrets/tasks/main.yml
- roles/generate-secrets/templates/copr.j2
- roles/generate-secrets/templates/fedora.toml.j2
- roles/generate-secrets/templates/packit-service.yaml.j2
- roles/generate-secrets/vars/main.yml
> add ansible playbook to generate local secrets

- Makefile
- README.md
- openshift/cert.yml.j2
- playbooks/get-certs.yml
* readme update
* get-certs now accepts domain instead of deployment
> polish docs and code for get certs & dashboard

- openshift/packit-service-centosmsg.yml.j2
- vars/template.yml
Use the values introduced in packit-service/packit-service-centosmsg#2.
> Configure CentOS MQTT listener

- Makefile
Fixes https://github.com/packit-service/packit-service/issues/590
> make hates spaces and needs a tab

- openshift/packit-service.yml.j2
see https://github.com/packit-service/packit-service/pull/596
I'll merge this next week after we see how the above PR works in production.
> [openshift/packit-service.yml.j2] lower resources requests/limits

- openshift/packit-service-centosmsg.yml.j2
Looking at metrics the pod has been using 20MiB constantly.
> [packit-service-centosmsg.yml.j2] Lower resource requests/limits

- README.md
Certificate renewal instruction updated using dns chalange approach.
> Certificate renewal instruction updated using dns chalange approach.

- playbooks/deploy.yml
- vars/template.yml
To be in sync with
https://github.com/packit-service/packit-service/blob/master/Makefile#L6
> [playbooks/deploy.yml] set container_engine conditionally

- cron-jobs/delete-pvcs/README.md
- cron-jobs/delete-pvcs/delete-pvcs.sh
this version has been running OK on `prod` & `stg`.
> Final version of delete-pvcs cron-job

- README.md
- cron-jobs/import-images/import-images.sh
- openshift/dashboard.yml.j2
- playbooks/deploy.yml
- vars/prod_template.yml
The dashboard is working now, so let's also deploy on prod.
> Deploy the dashboard on prod

- vars/stg_template.yml
> [vars/stg_template.yml] dashboard is deployed by default now

- README.md
- cron-jobs/delete-pvcs/README.md
- cron-jobs/delete-pvcs/delete-pvcs.sh
- cron-jobs/delete-pvcs/job-delete-pvcs.yaml
- cron-jobs/import-images/Makefile
- cron-jobs/import-images/README.md
- cron-jobs/import-images/import-images.sh
- cron-jobs/import-images/job-import-images.yaml
- openshift/packit-service-worker.yml.j2
- playbooks/deploy.yml
- vars/dev_template.yml
- vars/prod_template.yml
- vars/stg_template.yml
- vars/template.yml
Which I hit when trying to deploy to Openshift 4.
> Small technical debt fixes

- README.md
Related to packit-service/sandcastle#66
> [README.md] Add info about sandcastle stable branch

- playbooks/deploy.yml
Added onditional to process secrets/secrets.yaml only in `stg`
deployment stage.
> Deploy base image configuration fix

- openshift/github-app-private-key.yml.j2
- openshift/tokman.yml.j2
- playbooks/deploy.yml
- vars/dev_template.yml
- vars/prod_template.yml
- vars/stg_template.yml
- vars/template.yml
An internal service to manage GitHub App Tokens.
> Deploy tokman

- openshift/packit-service.yml.j2
Related to https://github.com/packit/packit-service/issues/778
> [openshift/packit-service.yml.j2] alembic upgrade head might need more memory

- openshift/tokman.yml.j2
https://github.com/packit/deployment/pull/118#discussion_r471415951
> Correct path to the tokman db file

- playbooks/deploy.yml
- vars/prod_template.yml
- vars/stg_template.yml
- vars/template.yml
They are not essential and we have them scaled down most of the time.
> Default with_flower and with_redis_commander to false

- openshift/nginx.yml.j2
This caused some troubles on stg, after removing this line, it should default to ClusterIP
> Change type of nginx service

- secrets/template/extra-vars.yml
This template is actually used when testing packit-service in Zuul.
> [secrets/template/extra-vars.yml] set meaningful postgres_host

- README.md
- playbooks/import-images.yml
- Update README to ask for moving the 'stable' branch in tokman.
- Update the import-images playbook to also import the centosmg listener and the tokman image.
> Assorted updates

- openshift/dashboard.yml.j2
- openshift/packit-service-fedmsg.yml.j2
- openshift/packit-service-worker.yml.j2
- openshift/tokman.yml.j2
Lower memory limits where possible in order to save some resources.
> Tweak memory limits

- secrets/template/packit-service.yaml
- Add `enabled_private_namespaces` field to the template config.
- Related PR: https://github.com/packit/packit-service/pull/831
> Enabled private namespaces

- containers/Dockerfile.base
I'm currently building/testing packit-service[-worker] with it.
> [containers/Dockerfile.base] FROM fedora:31 -> fedora:32

- containers/Dockerfile.base
each of our images installs something with pip3
> [containers/Dockerfile.base] install python3-pip

- Makefile
- cron-jobs/README.md
- playbooks/deploy.yml
- playbooks/rebuild-base-image.yml
- vars/infra_template.yml
Move oc cronjob `rebuild-base-image` to newly created packit-infra project.
> Cron job to packit infra

- Makefile
> Add Makefile target for moving stable branches

- cron-jobs/validation/openshift/job-run-validation.yaml
- cron-jobs/validation/packit-service-validation.py
- Set the maximum duration of the daily validation script
- Check whether the PR for the branch we want to create is not created yet
> [Validation script] Avoid exceptions

- cron-jobs/validation/README.md
- cron-jobs/validation/packit-service-validation.py
See individul commit messages for details.
> Misc validation fixes

- cron-jobs/delete-pvcs/Dockerfile
- cron-jobs/delete-pvcs/Makefile
- cron-jobs/delete-pvcs/job-delete-pvcs.yaml
And do some other adjustments on the way.
> Move delete-pvcs to Quay

- README.md
- openshift/dashboard.yml.j2
- playbooks/deploy.yml
- playbooks/import-images.yml
- playbooks/zuul-deploy.yml
- roles/generate-secrets/templates/packit-service.yaml.j2
- secrets/template/packit-service.yaml
- vars/dev_template.yml
- vars/prod_template.yml
- vars/stg_template.yml
- vars/template.yml
I'll test/merge this next week.
> Images are being moved from docker.io/usercont to quay.io/packit

- scripts/move_stable.py
- Allow moving only one repository
- Remove unused / commented out code for checking status of stage
- Warn and quit if directory with repositories is not present
Closes #161
> Refactor move-stable script

- openshift/packit-service.yml.j2
- openshift/packit-worker.yml.j2
> Use DISTGIT_URL env variable

- .github/workflows/base-image-rebuild.yml
> Run workflow on ubuntu-18.04

- roles/generate-secrets/templates/packit-service.yaml.j2
- secrets/template/packit-service.yaml
> Add dashboard URL to service configuration templates

- openshift/packit-service-centosmsg.yml.j2
packit/packit-service-centosmsg#29
> [centosmsg] define CELERY_DEFAULT_QUEUE env var

- containers/Dockerfile.base
Setting this interferes with locale.
> Don't set LANG in the base container

- playbooks/import-images.yml
The values can be changed in `vars/{{ service }}/{{ deployment }}.yml`
> import-images: define default values for used variables

- README.md
- openshift/repository-cache-filler.yml
Fixes the last part of packit/deployment#228
> Describe repository cache

- openshift/packit-worker.yml.j2
> Request packit-worker-repository-cache PVC if not with_repository_cache

- openshift/packit-worker.yml.j2
- openshift/sandcastle-volumes-for-cache.yml.j2
- playbooks/deploy.yml
- vars/packit/prod_template.yml
- vars/packit/stg_template.yml
And lower the size of the volume to 10Gi in prod so that we can add one more worker for long running tasks.
> Make the repo cache size configurable

- README.md
- playbooks/deploy.yml
so that the generated/renewed cert includes domains for stream service as well.
> Update 'Obtaining a cert via certbot' chapter

- openshift/packit-worker.yml.j2
- playbooks/deploy.yml
- vars/packit/dev_template.yml
- vars/packit/prod_template.yml
- vars/packit/stg_template.yml
- vars/stream/dev_template.yml
- vars/stream/prod_template.yml
- vars/stream/stg_template.yml
- vars/template.yml
> Hardly related changes

- scripts/gitlab_webhook.py
Hope there isn't one already :smile: 
> Write a script to generate secret tokens for GitLab webhooks

- containers/Dockerfile.base
- cron-jobs/delete-pvcs/Containerfile
- cron-jobs/import-images/Containerfile
- cron-jobs/packit-service-validation/Containerfile
> Bump all base images to fedora:35

- containers/Dockerfile.base
Fixes packit/packit-service#1274.
> Revert the base image to Fedora Linux 34

- cron-jobs/packit-service-validation/Containerfile
- cron-jobs/packit-service-validation/packit-service-validation.py
> Utilize GithubCheckRun.app property

- openshift/dashboard.yml.j2
That's what we have the image stream for - to be used in this DC.
> Use existing image stream in dashboard DeploymentConfig

- playbooks/cleanup.yml
- playbooks/import-images.yml
- scripts/setupcfg2rpm.py
There aren't too many left, so let's get rid of them.
> Update all old-style license headers

- playbooks/deploy.yml
It's been using 284M (271Mi) for last couple days.
Let's give it 256+64=320Mi
> Increase memory limit for short-running worker

- scripts/changelog.py
> Add script for getting changelog entries from the merge commits

- containers/Dockerfile.base
> Upgrade the base image to Fedora Linux 35

- .pre-commit-config.yaml
Upstream issue: https://github.com/pallets/click/issues/2232
> Update black version in pre-commit to fix the CI failures

- .ansible-lint
- .pre-commit-config.yaml
- cron-jobs/packit-service-validation/deploy-validation.yaml
- openshift/packit-worker.yml.j2
- playbooks/check.yml
- playbooks/cleanup.yml
- playbooks/deploy.yml
- playbooks/import-images.yml
- playbooks/tasks/check-pod-running.yml
- playbooks/tasks/k8s.yml
- playbooks/tasks/project-dir.yml
- playbooks/tasks/set-facts.yml
- playbooks/tasks/wait_for_pod.yml
- playbooks/zuul-check.yml
- playbooks/zuul-deploy.yml
- playbooks/zuul-secrets.yml
- roles/generate-secrets/tasks/create-directories.yml
- roles/generate-secrets/tasks/generate-cert.yml
- roles/generate-secrets/tasks/generate-configs.yml
- roles/generate-secrets/tasks/project-dir.yml
- roles/generate-secrets/tasks/touch-files.yml
- vars/fedora-source-git/stg_template.yml
- vars/packit/stg_template.yml
- vars/stream/stg_template.yml
This is a mix of several refactoring-ish changes, I don't think it makes sense to split them into several PRs.
I know it's risky to approve when we don't have working tests at the moment, but you have to trust me that I tested on all our projects in the new auto-stage cluster ;-)
> Auto-stage cluster & ansible-lint v6

- cron-jobs/packit-service-validation/README.md
- cron-jobs/packit-service-validation/deploy-validation.yaml
- cron-jobs/packit-service-validation/openshift/job-run-validation.yml.j2
- cron-jobs/packit-service-validation/packit-service-validation.py
> Differentiate tests by deployment

- cron-jobs/packit-service-validation/README.md
Add URLs to clarify where secrets have to be taken.
> Enhance README for a newbie

- .github/workflows/build-and-push-cronjob-image.yaml
Should fix the following error:
Input "tags" cannot have a mix of full name and non full name tags
> Fix mix of full name and non full name tags

- .github/workflows/build-and-push-cronjob-image.yaml
This time seems to be working at least in my fork, however I leaved the empty line commit to trigger the build in the main branch.
> Calculate short SHA using bash

- openshift/postgres.yml.j2
The changes are already deployed, no need to apply/redeploy anything.
> Postgres resources and config changes

- .ansible-lint
- docs/monitoring.md
- openshift/flower.yml
- openshift/nginx.yml.j2
- openshift/secret-flower-htpasswd.yml.j2
- playbooks/deploy.yml
- playbooks/tasks/set-facts.yml
- playbooks/zuul-deploy.yml
- vars/packit/dev_template.yml
- vars/packit/prod_template.yml
- vars/packit/stg_template.yml
Use flower service to collect celery related metrics (https://issues.redhat.com/browse/PACKIT-1109).
Related with packit/packit-service#1561
> Celery_metrics

- scripts/move_stable.py
And allow to select the period for which the Git history of the selected
repositories is searched for release notes.
> move_stable: add a new command to create a blog post

- containers/Dockerfile.base
To be able to easily enable/disable copr repos.
> Add community.general Ansible collection

- openshift/packit-worker.yml.j2
- vars/packit/prod_template.yml
- vars/packit/stg_template.yml
I'll merge once this proves to work on prod. Let's discuss it meanwhile.
> Autoscale prod short-running worker & make stg workers layout similar to prod

- openshift/packit-worker.yml.j2
packit/packit-service@4ec0024c
> Define CONCURRENCY env. variable instead of AUTOSCALE

- openshift/packit-service-beat.yml.j2
- openshift/packit-service.yml.j2
- openshift/packit-worker.yml.j2
- openshift/postgres.yml.j2
because the files are getting quite long.
And remove [long-time unused probes](https://github.com/packit/deployment/pull/142).
> Represent dicts in abbreviated form

- vars/fedora-source-git/stg_template.yml
- vars/packit/stg_template.yml
- vars/stream/stg_template.yml
> chore: move from auto-stage to auto-prod

- openshift/packit-worker.yml.j2
- playbooks/deploy.yml
- vars/fedora-source-git/prod_template.yml
- vars/packit/prod_template.yml
- vars/stream/prod_template.yml
and stop sending logs to files, we finally seem to have a working token for Splunk HEC.
> Deploy Fluentd sidecar conditionally

- openshift/packit-service-fedmsg.yml.j2
- playbooks/check.yml
- playbooks/cleanup.yml
- playbooks/deploy.yml
- playbooks/import-images.yml
- playbooks/tasks/project-dir.yml
- playbooks/zuul-deploy.yml
- playbooks/zuul-secrets.yml
- roles/generate-secrets/tasks/project-dir.yml
Use the default command specified in the [Dockerfile](https://github.com/packit/packit-service-fedmsg/blob/main/Dockerfile#L20).
https://github.com/packit/packit-service-fedmsg/pull/73
> Don't specify command to run in packit-service-fedmsg pod

- docs/centos-stream-source-git.md
> Describe redhat-internal-test-package in Stream source-git README

- openshift/postgres.yml.j2
- openshift/redis.yml
- openshift/tokman.yml.j2
- playbooks/check.yml
- playbooks/deploy.yml
- playbooks/render_secrets_from_templates.yml
- playbooks/tasks/check-pod-running.yml
- playbooks/tasks/k8s.yml
- playbooks/tasks/project-dir.yml
- roles/generate-secrets/tasks/main.yml
- roles/generate-secrets/tasks/project-dir.yml
> CentOS Stream based sclorg postgres & redis images

- .ansible-lint
- .pre-commit-config.yaml
- playbooks/deploy.yml
- playbooks/zuul-secrets.yml
- scripts/render_secrets_from_templates.sh
- scripts/update_bw_secret.sh
- scripts/update_oc_secret.sh
> Add shellcheck to pre-commit config

- secrets/packit/prod/packit-service.yaml.j2
Requested by rolivier@redhat.com .
> Allow some leapp repositories to test in internal TF

- openshift/packit-worker.yml.j2
- vars/packit/prod_template.yml
to ensure it's not causing packit/packit-service#1728 & packit/packit-service#1763
> Temporarily disable multi-threaded worker

- secrets/packit/stg/fedora.toml.j2
Related to packit/packit-service#1577
> [packit-stg fedora.toml.j2] add New hotness topic

- containers/Dockerfile.base
> Bump base image to Fedora 37

- secrets/packit/prod/fedora.toml.j2
Add the org.fedoraproject.prod.hotness.update.bug.file topic to the routing keys for prod Packit.
> [packit-prod fedora.toml.j2] add New hotness topic

- cron-jobs/import-images/Containerfile
https://bugzilla.redhat.com/show_bug.cgi?id=2111500
and use c9s as a base image.
> Install OKD CLI (oc)

- playbooks/tasks/check-pod-running.yml
- playbooks/tasks/set-facts.yml
labels have changed since c2b51621
> Update label selector

- scripts/move_stable.py
This also prints latest builds of our packages.
> move-stable: make specific instructions more visible

- docs/continuous-deployment.md
- docs/tls-certs.md
- playbooks/deploy.yml
and fix triggers(notify) due to handlers being renamed in 75495bb5
> Update Redeploy-secrets section in docs/tls-certs.md 

- scripts/changelog.py
Just a copy of https://github.com/packit/prepare-release/pull/10
> Consider new format for PR ID parsing

- cron-jobs/import-images/import-images.sh
- openshift/packit-service-fedmsg.yml.j2
- secrets/fedora-source-git/prod/fedora.toml.j2
- secrets/fedora-source-git/stg/fedora.toml.j2
- secrets/packit/prod/fedora.toml.j2
- secrets/packit/stg/fedora.toml.j2
Related to packit/packit-service-fedmsg#76
> Fedmsg liveness probe

- cron-jobs/packit-service-validation/README.md
- cron-jobs/packit-service-validation/packit-service-validation.py
> GitLab validation 

- openshift/packit-service-fedmsg.yml.j2
Needed for packit/packit-service-fedmsg#78
> Set PROJECT env. var. in fedmsg pod

- openshift/packit-worker.yml.j2
Related to packit/packit-service#1948
> feat: add environment variable for user agent

- secrets/fedora-source-git/prod/fedora.toml.j2
- secrets/fedora-source-git/stg/fedora.toml.j2
> Add git.receive to fedora-source-git fedora.tomls

- openshift/packit-worker.yml.j2
- playbooks/deploy.yml
- vars/fedora-source-git/prod_template.yml
- vars/fedora-source-git/stg_template.yml
We haven't had a staging instance yet, hence the 'SETME'.
Related packit/hardly#92
> Set SOURCEGIT_NAMESPACE env. var. for fedora-source-git

- secrets/packit/prod/packit-service.yaml.j2
- secrets/packit/stg/packit-service.yaml.j2
Fixes packit/packit-service#2003
> chore: add Nikola to admins

- openshift/packit-worker.yml.j2
- openshift/postgres.yml.j2
- openshift/redis.yml.j2
- openshift/sandcastle-volumes-for-cache.yml.j2
- openshift/tokman.yml.j2
- playbooks/check.yml
- playbooks/deploy.yml
- playbooks/tasks/set-facts.yml
- vars/fedora-source-git/prod_template.yml
- vars/fedora-source-git/stg_template.yml
- vars/packit/dev_template.yml
- vars/packit/prod_template.yml
- vars/packit/stg_template.yml
- vars/stream/dev_template.yml
- vars/stream/prod_template.yml
- vars/stream/stg_template.yml
- vars/template.yml
> More MP+ related tuning

- cron-jobs/packit-service-validation/packit-service-validation.py
Fix token name, aligned with the one in the Helm chart
> Fix SALSA_DEBIAN_TOKEN name in script

- README.md
- openshift/dashboard.yml.j2
- openshift/nginx.yml.j2
- openshift/packit-service-beat.yml.j2
- openshift/packit-service.yml.j2
- openshift/pushgateway.yml.j2
- playbooks/deploy.yml
- playbooks/import-images.yml
- playbooks/tasks/set-facts.yml
- secrets/packit/stg/packit-service.yaml.j2
- vars/packit/stg_template.yml
Took #483, rebased, applied my comments, and added a few commits on top.
> MP+ migration

- docs/deployment/tls-certs.md
Wildcard certificates are not allowed (packit/private#27) so we must enumerate all the subdomains when generating a new cert.
> Update TLS cert HOWTO

- scripts/move_stable.py
Current state can be seen at https://github.com/packit/production-monorepo
> feat(move-stable): track the deployments

- docs/deployment/openshift_local_cluster.md
Thank you Tomas Tomecek for all your help!
> Brief guide for using Openshift Local

- secrets/packit/prod/packit-service.yaml.j2
- secrets/packit/stg/packit-service.yaml.j2
> Allow some projects from github.com/container to use internal TF

- secrets/packit/prod/packit-service.yaml.j2
- secrets/packit/stg/packit-service.yaml.j2
> Allow github.com/ptoscano/insights-client to use internal TF

- secrets/packit/prod/fedora.toml.j2
- secrets/packit/stg/fedora.toml.j2
Related to packit/packit-service#2305
Merge after packit/packit-service#2351
> Migrate to org.fedoraproject.prod.pagure.git.receive

- secrets/packit/prod/packit-service.yaml.j2
- secrets/packit/stg/packit-service.yaml.j2
> Allow github.com/theforeman/foreman-installer to use internal TF

- vars/packit/prod_template.yml
As I promised @majamassarini and forgot /o
> fix(vars): adjust the number of deployed workers

- secrets/packit/prod/packit-service.yaml.j2
- secrets/packit/stg/packit-service.yaml.j2
Related to https://github.com/packit/specfile/pull/385.
> Allow specfile to use internal TF

- secrets/packit/prod/fedora.toml.j2
- secrets/packit/stg/fedora.toml.j2
Related to https://github.com/packit/packit-service/issues/2378.
> Listen for org.fedoraproject.prod.buildsys.tag messages

- secrets/packit/prod/packit-service.yaml.j2
- secrets/packit/stg/packit-service.yaml.j2
TODO:
Fixes
Related to
Merge before/after
RELEASE NOTES BEGIN
Packit now supports automatic ordering of ☕ after all checks pass.
RELEASE NOTES END
> Allow containers/common to use internal TF

- secrets/packit/stg/packit-service.yaml.j2
While the testing farm staging instance is not available
> Use testing farm production instance in packit stage instance

- openshift/packit-service.yml.j2
- openshift/packit-worker.yml.j2
- vars/packit/prod_template.yml
- vars/packit/stg_template.yml
* Drop deployment of tokman
* Mount GitHub App private key
* Adjust the variables in templates
TODO:
Fixes packit/tokman#72
> fix: drop tokman deployment

- docs/deployment/resource-requirements.md
Fixes
Related to #584
Merge before/after
> docs: document the resource requirements

- secrets/packit/prod/fedora.toml.j2
- secrets/packit/stg/fedora.toml.j2
Related to packit/packit-service#2543
Merge before packit/packit-service-fedmsg/pull/113
> Allow OpenScanHub task finish message in queue

- secrets/packit/prod/fedora.toml.j2
- secrets/packit/stg/fedora.toml.j2
Related to https://github.com/packit/packit-service/pull/2580
> Allow both started and finished OpenScanHub msgs in queue

- secrets/packit/prod/fedora.toml.j2
- secrets/packit/stg/fedora.toml.j2
Related to packit/packit-service#2579
> Configure listening to PR related fedmsg topics

- roles/deploy/tasks/main.yml
I just realized I forgot the long running workers and looking at the metrics we sometime hit the limit also here...
> Increase cpu limits for long running workers

- secrets/packit/prod/centpkg-sig.conf.j2
- secrets/packit/prod/packit-service.yaml.j2
- secrets/packit/stg/centpkg-sig.conf.j2
- secrets/packit/stg/packit-service.yaml.j2
- tasks/set-facts.yml
Fixes packit/private#41
TODO:
Fixes packit/private#41
> feat: handle tokens via Bitwarden Vault
